### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by croketillo** [elkinaguas/clir#4]
Trying save a new comand:

Traceback (most recent call last):
  File "/home/XXXX/.local/bin/clir", line 8, in <module>
    sys.exit(cli())
  File "/home/xxx/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/xxxx/.local/lib/python3.10/site-packages/rich_click/rich_command.py", line 126, in main
    rv = self.invoke(ctx)
  File "/home/xxxx/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/xxxx/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/xxxx/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/xxxx/.local/lib/python3.10/site-packages/clir/cli.py", line 38, in new
    new_command.save_command()
  File "/home/xxx/.local/lib/python3.10/site-packages/clir/utils/objects.py", line 36, in save_command
    current_commands[str(command)] = {"description": desc, "tag": tag, "uid": str(uid)}
TypeError: list indices must be integers or slices, not str

**Comment by elkinaguas** [comment]
Hello, which OS and OS version are you using?

**Comment by croketillo** [comment]
hello!

I got the error using Ubuntu 22.04.3 LTS.

However, I was watching it slowly... I had the error for using 'pip' in the installation instead of 'pip3'.
 
I don't know why this happened to me because:
'pip --version' => pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

'pip3 --version' => pip 22.0.2 from /usr/lib/python3/dist-packages/pip (python 3.10)

Using pip3 it works correctly.

**Comment by elkinaguas** [comment]
Hello @croketillo,

I was able to reproduce the error. You actually found a bug! :)

The problem happens when someone tries to save a new command before having initialized Clir using `clir init`.

You can go ahead and patch it if you feel like contributing to the project! Let me know if I can help with anything.

Thanks for using Clir!

**Comment by croketillo** [comment]
Hello again! Glad to try collaborating, but I must warn you that I am an amateur developer. I'll be submitting pull requests! in case it's helpful.  Thank you, clir is helpful to me.

**Comment by elkinaguas** [comment]
The code you proposed did the trick, nicely done. Your changes will be included in the next release. Thank you for your contribution, and I'm happy you find Clir useful! Feel free to propose any changes, improvements, or even new features :)

I'll close the issue now.

Best,
Elkin
